[package]
name = "rust-functions"
authors = ["Bob Irving"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
hyper = "0.14.27"
serde = "1.0.183"
serde_json = "1.0.105"
tokio = {version = "1.32.0", features = ["full"]}
wasm-bindgen = "0.2.87"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
